# Site settings
title: Eddie Fu
email: eddie.h.fu@gmail.com
url: https://nbfuhao.github.io
description: "Lead iOS Developer @ LiveAuctioneers, Hacking @ github.com/nbfuhao"
skills: "iOS Developer, Objective C & Swift"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/in/nbfuhao
  - title: stack-overflow
    url: http://stackoverflow.com/users/3873081/eddiehfu
  - title: github
    url: http://github.com/nbfuhao

# Postal address (add as many lines as necessary)
address:
  - line: New York City

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme'

# Build settings
markdown: kramdown
permalink: pretty
